{{- if .Values.certificate.enabled }}
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: {{ include "no-fucking-thing-backend.fullname" . }}-tls-cert
  annotations:
    "helm.sh/hook-weight": "-1"
spec:
  {{- with .Values.certificate.domains }}
    domains:
      {{- toYaml . | nindent 6 }}
  {{- end }}
{{- end }}