ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-default-lb"
    networking.gke.io/managed-certificates: "no-fucking-thing-frontend-tls-cert"
    kubernetes.io/ingress.allow-http: "false"
  hosts:
    - host: insider.trapp.io
      paths:
        - path: /*
          pathType: ImplementationSpecific

certificate:
  enabled: true
  domains: [insider.trapp.io]
