# Set all environment variables required to run the ui.
env:
  - name: NETWORK_URL
    value: "https://bombay-lcd.terra.dev"
  - name: CHAIN_ID
    value: "bombay-12"
  - name: MARKETPLACE_ADDRESS
    value: "terra18yk3tzwkrte5jnmwuru3ht3tjxk7uysc7kksxy"
  - name: GEN0_ADDRESS
    value: "terra1c58xptzpcwrz79qa50m67fr77zehyhfs0hpg7m"
  - name: BACKEND_REST_API_ENDPOINT
    value: "apis.insider.trapp.io"

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-default-lb"
    networking.gke.io/managed-certificates: "no-fucking-thing-frontend-tls-cert"
  hosts:
    - host: insider.trapp.io
      paths:
        - path: /*
          pathType: ImplementationSpecific

certificate:
  enabled: true
  domains: [insider.trapp.io]
